/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projektpo;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateusz
 */
public class GUI extends javax.swing.JFrame {
    /**
     * Creates new form GUI
     */
    public CentrumObslugi centrum;
    public GUI(CentrumObslugi centrum) {
        initComponents();
        this.centrum = centrum;      
        ImageIcon icon = new ImageIcon("icon.png");
        setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Firmy = new javax.swing.JMenu();
        OpcjeFirmy = new javax.swing.JMenuItem();
        Banki = new javax.swing.JMenu();
        OpcjeBanku = new javax.swing.JMenuItem();
        Klienci = new javax.swing.JMenu();
        OpcjeKlienta = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Konta = new javax.swing.JMenu();
        OpcjeKonta = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Transaction = new javax.swing.JMenu();
        NewTransaction = new javax.swing.JMenuItem();
        OldTransaction = new javax.swing.JMenuItem();
        Load = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenu();
        EXIT = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Centrum Obsługi ");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/tytul.jpg"))); // NOI18N

        Firmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/icons8-company-25.png"))); // NOI18N
        Firmy.setText("Firmy       ");
        Firmy.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N

        OpcjeFirmy.setText("Opcje firmy");
        OpcjeFirmy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcjeFirmyActionPerformed(evt);
            }
        });
        Firmy.add(OpcjeFirmy);

        Menu.add(Firmy);

        Banki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/icons8-bank-25.png"))); // NOI18N
        Banki.setText("Banki       ");
        Banki.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N

        OpcjeBanku.setText("Opcje banku");
        OpcjeBanku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcjeBankuActionPerformed(evt);
            }
        });
        Banki.add(OpcjeBanku);

        Menu.add(Banki);

        Klienci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/icons8-client-25.png"))); // NOI18N
        Klienci.setText("Klienci       ");
        Klienci.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N

        OpcjeKlienta.setText("Dodaj klienta");
        OpcjeKlienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcjeKlientaActionPerformed(evt);
            }
        });
        Klienci.add(OpcjeKlienta);

        jMenuItem3.setText("Usuń klienta");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Klienci.add(jMenuItem3);

        jMenuItem1.setText("Lista klientów");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Klienci.add(jMenuItem1);

        Menu.add(Klienci);

        Konta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/icons8-account-25 (1).png"))); // NOI18N
        Konta.setText("Konta       ");
        Konta.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N

        OpcjeKonta.setText("Opcje konta");
        OpcjeKonta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcjeKontaActionPerformed(evt);
            }
        });
        Konta.add(OpcjeKonta);

        jMenuItem4.setText("Bankomat");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Konta.add(jMenuItem4);

        Menu.add(Konta);

        Transaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/icons8-card-payment-25.png"))); // NOI18N
        Transaction.setText("Transakcje       ");
        Transaction.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N

        NewTransaction.setText("Nowa");
        NewTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewTransactionActionPerformed(evt);
            }
        });
        Transaction.add(NewTransaction);

        OldTransaction.setText("Zrealizowane");
        OldTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OldTransactionActionPerformed(evt);
            }
        });
        Transaction.add(OldTransaction);

        Menu.add(Transaction);

        Load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/icons8-save-25.png"))); // NOI18N
        Load.setText("Zapisz       ");
        Load.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N

        jMenuItem2.setText("Zapisz aktualny stan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Load.add(jMenuItem2);

        Menu.add(Load);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/icons8-exit-25.png"))); // NOI18N
        Exit.setText("Wyjście       ");
        Exit.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N

        EXIT.setText("Exit");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        Exit.add(EXIT);

        Menu.add(Exit);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewTransactionActionPerformed
        // TODO add your handling code here:
        new GUINewTransaction(centrum).setVisible(true);
    }//GEN-LAST:event_NewTransactionActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void OldTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OldTransactionActionPerformed
        // TODO add your handling code here:
        new GUIOldTransaction(centrum).setVisible(true);
        
    }//GEN-LAST:event_OldTransactionActionPerformed

    private void OpcjeFirmyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcjeFirmyActionPerformed
        // TODO add your handling code here:
        new GUIOptionCompany(centrum).setVisible(true);
    }//GEN-LAST:event_OpcjeFirmyActionPerformed

    private void OpcjeBankuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcjeBankuActionPerformed
        // TODO add your handling code here:
        new GUIOptionBank(centrum).setVisible(true);
    }//GEN-LAST:event_OpcjeBankuActionPerformed

    private void OpcjeKlientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcjeKlientaActionPerformed
        // TODO add your handling code here:
        new GUIOptionClient(centrum).setVisible(true);
    }//GEN-LAST:event_OpcjeKlientaActionPerformed

    private void OpcjeKontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcjeKontaActionPerformed
        // TODO add your handling code here:
        new GUIOptionAccount(centrum).setVisible(true);
    }//GEN-LAST:event_OpcjeKontaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
            centrum.zapisywanie();
            centrum.wyswietlFirmy();
            centrum.wyswietlBanki();
            centrum.bazaDanychCentrum.wyswietlTransakcje();
            JOptionPane.showMessageDialog(this, "Zapisano stan");
        }  catch (Exception e) {
            System.out.println("nie dziala");
            JOptionPane.showMessageDialog(this, "Nie udalo sie zapisać stanu");
        }      
      
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new GUIListClient(centrum).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new GUIRemoveClient(centrum).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new GUIAddFunds(centrum).setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI(centrum).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Banki;
    private javax.swing.JMenuItem EXIT;
    private javax.swing.JMenu Exit;
    private javax.swing.JMenu Firmy;
    private javax.swing.JMenu Klienci;
    private javax.swing.JMenu Konta;
    private javax.swing.JMenu Load;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem NewTransaction;
    private javax.swing.JMenuItem OldTransaction;
    private javax.swing.JMenuItem OpcjeBanku;
    private javax.swing.JMenuItem OpcjeFirmy;
    private javax.swing.JMenuItem OpcjeKlienta;
    private javax.swing.JMenuItem OpcjeKonta;
    private javax.swing.JMenu Transaction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
